# Generated by Django 5.2.8 on 2025-11-20 14:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
