# Generated by Django 5.2.8 on 2025-11-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_about_bio_alter_home_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='keywords',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
