# Generated by Django 5.2.8 on 2025-11-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_home_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
